"use client";

import { Suspense } from "react";

import { DailyForecast } from "@/components/daily-forecast";
import { ErrorState } from "@/components/error-state";
import { HourlyForecast } from "@/components/hourly-forecast";
import { LocationUrlSync } from "@/components/location-url-sync";
import { WeatherCardSkeleton } from "@/components/skeletons";
import { useWeather } from "@/context/weather-context";

export function ForecastView() {
  const { data, loading, error, refresh } = useWeather();

  return (
    <div className="space-y-6">
      <Suspense fallback={null}>
        <LocationUrlSync />
      </Suspense>
      <header className="space-y-1">
        <h1 className="text-3xl font-extrabold tracking-tight text-slate-900 dark:text-white">
          Forecast
        </h1>
        <p className="text-slate-500 dark:text-slate-400">
          Hour-by-hour and multi-day outlook for{" "}
          {data?.current.location ?? "your location"}.
        </p>
      </header>

      {loading && !data && <WeatherCardSkeleton />}
      {error && !data && (
        <ErrorState message={error.message} onRetry={() => void refresh()} />
      )}
      {data && (
        <div className="space-y-8">
          <HourlyForecast
            hourly={data.forecast.hourly}
            timezoneOffset={data.current.timezoneOffset}
          />
          <DailyForecast
            daily={data.forecast.daily}
            timezoneOffset={data.current.timezoneOffset}
          />
          <p className="rounded-2xl border border-white/10 bg-white/40 px-4 py-3 text-sm text-slate-500 dark:bg-white/5 dark:text-slate-400">
            Forecasts are generated by OpenWeather and update automatically. Timestamps reflect
            local time in {data.current.location}.
          </p>
        </div>
      )}
    </div>
  );
}
